markdown: rdiscount
pygments: true
permalink: /posts/:title
auto: true
rdiscount:
  extensions: [smart]

name: Fred McHale
url: http://binaryfever.com
description: The greatest blog on earth.
twitter: binaryfever
github: binaryfever
gravatar_url: http://gravatar.com/avatar/3f08635fd0735da301cd8d51acb1f51a